### Create POST
POST http://localhost:5000/api/tasks
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NjNTk5MDhhYjljZjI2ZDdiY2FlNjAiLCJyb2xlIjoiVXNlciIsImlhdCI6MTc0MTQ0OTY2NCwiZXhwIjoxNzQxNDUzMjY0fQ.A1yxTc4iZvEhUcdFoMS8lW-Rong_tVm4H-2eLqn-KFE

{
  "title":"study for exam", 
  "description":"Math and Science"
}

### GET ALL
GET http://localhost:5000/api/tasks
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NjNTk5MDhhYjljZjI2ZDdiY2FlNjAiLCJyb2xlIjoiVXNlciIsImlhdCI6MTc0MTQ0OTg1OSwiZXhwIjoxNzQxNDUzNDU5fQ.UU_MOHy-3G1gZOzedt6BLJ4mEu5qry8i_0vFX_1RPIk

### GET By ID
GET http://localhost:5000/api/tasks/67cc61b731bb509bf2e2a0f0
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NiZTczNzFlMjM4NzA0YTVhMGFmNGYiLCJyb2xlIjoiVXNlciIsImlhdCI6MTc0MTQ0NzUzNiwiZXhwIjoxNzQxNDUxMTM2fQ.6144OlZZ9BYCJLWa1nL8eDIUHk4yCYFMODV-t_YCGaU


### Update By ID
PUT http://localhost:5000/api/tasks/67cc61b731bb509bf2e2a0f0
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NiZTczNzFlMjM4NzA0YTVhMGFmNGYiLCJyb2xlIjoiVXNlciIsImlhdCI6MTc0MTQ0NzUzNiwiZXhwIjoxNzQxNDUxMTM2fQ.6144OlZZ9BYCJLWa1nL8eDIUHk4yCYFMODV-t_YCGaU

{
  "title": "cleaning activity",
  "description": "cleaning the house",
  "status": "In Progress",
  "completed":false
}

### Delete By ID
DELETE http://localhost:5000/api/tasks/67cc618e31bb509bf2e2a0e1
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NiZTczNzFlMjM4NzA0YTVhMGFmNGYiLCJyb2xlIjoiVXNlciIsImlhdCI6MTc0MTQ0NzUzNiwiZXhwIjoxNzQxNDUxMTM2fQ.6144OlZZ9BYCJLWa1nL8eDIUHk4yCYFMODV-t_YCGaU


### admin role, get task
GET http://localhost:5000/api/tasks
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2NjNWM0NzgxMGIzNDZhZGI4NmM5NTciLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3NDE0NDk5MTksImV4cCI6MTc0MTQ1MzUxOX0.uRLWR_zPi4XTeFRaesVZwFeQMTVnGc1B3-nt2jhkAQ4
Content-Type: application/json