POST http://localhost:5000/api/auth/login
Content-Type: application/json
    
{
    "email": "admin@example.com",
    "password": "admin"
}

### user login
POST http://localhost:5000/api/auth/login
Content-Type: application/json
    
{
    "email": "user@example.com",
    "password": "admin"
}

### Create a User
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "yourpassword"
}

### create an Admin user
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "email": "abc2@example.com",
  "password": "dmin",
  "role": "Admin" 
}


### invalid user login
POST http://localhost:5000/api/auth/login
Content-Type: application/json
    

{
  
  "password": "validpassword123"
}
